{
	"version": 1558407221,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/slid1.png",
		"images/butonmanu1-sheet0.png",
		"images/btmanu2-sheet0.png",
		"images/btmanu3-sheet0.png",
		"images/btmanu4-sheet0.png",
		"images/exit-sheet0.png",
		"images/aboutbut-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bggame-sheet0.png",
		"images/targetgame-sheet0.png",
		"images/keepergmae-sheet0.png",
		"images/ballgame-sheet0.png",
		"images/bggame2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/lette-sheet0.png",
		"images/lette-sheet1.png",
		"images/lette-sheet2.png",
		"images/drop1-sheet0.png",
		"images/book1-sheet0.png",
		"images/particles.png",
		"images/btnext-sheet0.png",
		"images/bgtest-sheet0.png",
		"images/bgtext-sheet0.png",
		"images/testc1-sheet0.png",
		"images/testc2-sheet0.png",
		"images/testc3-sheet0.png",
		"images/testc4-sheet0.png",
		"images/bgevoluation-sheet0.png",
		"images/bgtohome-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/scrollpage-sheet0.png",
		"images/bggamehub-sheet0.png",
		"images/gogame1-sheet0.png",
		"images/gogame2-sheet0.png",
		"images/bgvideo-sheet0.png",
		"images/bgaboutme-sheet0.png",
		"images/bglogin-sheet0.png",
		"images/poppup-sheet0.png",
		"images/btlogin-sheet0.png",
		"images/bgwellcome-sheet0.png",
		"images/btlogout-sheet0.png",
		"images/title-sheet0.png",
		"images/spritefont2.png",
		"images/btplay-sheet0.png",
		"images/btpaus-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/bgt2-sheet0.png",
		"images/bgt3-sheet0.png",
		"images/bgt4-sheet0.png",
		"images/bgt5-sheet0.png",
		"images/bgt6-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/gotoweb-sheet0.png",
		"media/กระดิ่ง 4 (online-audio-converter.com).ogg",
		"media/กระจก 1.ogg",
		"media/กระจก 2.ogg",
		"media/กระดิ่ง 1.ogg",
		"media/กระดิ่ง 2.ogg",
		"media/กระดิ่ง 4.ogg",
		"media/กราวกีฬา.ogg",
		"media/ค้างคาวกินกล้วย.ogg",
		"media/จน เครียด กินเหล้า.ogg",
		"media/จิ้งหรีด.ogg",
		"media/ช้าง.ogg",
		"media/ตบมือ 1.ogg",
		"media/ตบมือ 2.ogg",
		"media/ตลก 1.ogg",
		"media/ตลก 10.ogg",
		"media/ตลก 11.ogg",
		"media/ตลก 12.ogg",
		"media/ตลก 13.ogg",
		"media/ตลก 14.ogg",
		"media/ตลก 15.ogg",
		"media/ตลก 16.ogg",
		"media/ตลก 17.ogg",
		"media/ตลก 18.ogg",
		"media/ตลก 19.ogg",
		"media/ตลก 2.ogg",
		"media/ตลก 20.ogg",
		"media/ตลก 21.ogg",
		"media/ตลก 22.ogg",
		"media/ตลก 3.ogg",
		"media/ตลก 4.ogg",
		"media/ตลก 5.ogg",
		"media/ตลก 6.ogg",
		"media/ตลก 7.ogg",
		"media/ตลก 8.ogg",
		"media/ตลก 9.ogg",
		"media/ตุ๊กแก.ogg",
		"media/ธรณีกรรแสง.ogg",
		"media/นก 1.ogg",
		"media/นก 2.ogg",
		"media/นก 3.ogg",
		"media/บรรเลงโหมโรง.ogg",
		"media/บ่นอีสาน.ogg",
		"media/ฝนตก.ogg",
		"media/เด็กร้องไห้.ogg",
		"media/เปิดตัวจีน.ogg",
		"media/เปิดตัวสากล.ogg",
		"media/แกะ.ogg",
		"media/แตรรถ.ogg",
		"media/ไก่ 1.ogg",
		"media/ไก่ 2.ogg",
		"media/1.ogg",
		"media/10-12.ogg",
		"media/2.ogg",
		"media/3-4.ogg",
		"media/5-6เ.ogg",
		"media/7-9.ogg",
		"media/start.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"vooo.webm"
	]
}